### ISSUE TITLE
Fix for FirstPersonController.hx btvec.z "btscalar should be int" error on build

### ISSUE THREAD

**Issue by rt974** [deprecated-armory3d/armory_templates_b27#2]
Never used Haxe before, took me some time to figure out what the heck was wrong with this code.

I looked at Bullet.hx, and it turns out that this is not a variable but a function.
Adding parenthesis fixed the error, and the demo runs fine.

btvec.z ---> btvec.z( )

I think the haxe error is not reported correctly, in most langages i used, when you write a function name without parenthesis, it says that variable/member doesnt exist.

**Comment by luboslenco** [comment]
Heyo,

If you use 'stable' Armory 0.3 then always download the appropriate release:
https://github.com/armory3d/armory_templates/releases

And if you use the latest Armory through git / [armory updater](http://armory3d.org/manual/#/dev/gitversion?id=armory-updater), then the latest version of this repository should (hopefully!) work as well.

**Comment by rt974** [comment]
i just cloned the github repos for the templates, and opened them with v0.3 from itch.io patreon access.

**Comment by luboslenco** [comment]
Yes, the issue is that by cloning you get the latest version of this repository which is developed alongside the upcoming armory 0.4. If you download the zip from the releases at https://github.com/armory3d/armory_templates/releases/tag/18.03a then that should work. (Or updating to the latest armory using the updater and then using the cloned version of armory_templates).

And I should clarify this in the docs, sorry for trouble.

**Comment by luboslenco** [comment]
Should now be resolved with 0.4 builds.
